/** Run after changing code/assets and after generating preview atlases. No dependencies. */
import {createHash} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {readdir, readFile, stat, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root = fileURLToPath(new URL('../', import.meta.url));
const roots = ['apps', 'core', 'gtatlas', 'gtasset', 'gtfx', 'gtmap', 'resources', 'shared', 'vendor'];
// A pinned GitHub URL must never silently serve an older copy of changed assets.
const config = await readFile(path.join(root,'core/delivery-config.js'),'utf8');
const snapshot = config.match(/cdnBase:\s*['"]https:\/\/cdn\.jsdelivr\.net\/gh\/[^'"\s]+@([a-f0-9]{40})\/gtlibrary\//);
const assetFolders=['gtatlas/assets/','gtasset/assets/','gtfx/assets/'];
const expectedAssets=new Map();
if(snapshot){
  // Read the committed tree directly; this also avoids relying on the user's index.
  const tree=execFileSync('git',['ls-tree','-r','-z',snapshot[1],'--',...assetFolders],{cwd:root,encoding:'utf8',maxBuffer:4*1024*1024});
  for(const entry of tree.split('\0').filter(Boolean)){
    const [header,file]=entry.split('\t');expectedAssets.set(file,header.split(' ')[2]);
  }
  if(!expectedAssets.size)throw new Error('The pinned CDN commit contains no matching assets.');
}
async function walk(folder) {
  const files = [];
  for (const item of await readdir(path.join(root, folder), {withFileTypes: true})) {
    const relative = path.posix.join(folder, item.name);
    if (item.isDirectory()) files.push(...await walk(relative));
    else if (relative !== 'core/cache-version.js') files.push(relative);
  }
  return files;
}
const files = ['index.html', 'library.js', 'library.css', 'sw.js'];
for (const folder of roots) files.push(...await walk(folder));
const hash = createHash('sha256');
for (const file of files.sort()) {
  hash.update(file + '\0');
  const fileHash = createHash('sha256');
  const checkAsset=snapshot&&assetFolders.some(folder=>file.startsWith(folder));
  const gitHash=checkAsset?createHash('sha1'):null;
  if(gitHash)gitHash.update('blob '+(await stat(path.join(root,file))).size+'\0');
  for await (const chunk of createReadStream(path.join(root, file))){fileHash.update(chunk);gitHash?.update(chunk);}
  if(gitHash){
    let actual=gitHash.digest('hex');
    // Windows checkouts may convert committed LF text to CRLF.
    if(actual!==expectedAssets.get(file)&&/\.(?:js|json|atlas|txt)$/.test(file)){
      const normalized=Buffer.from((await readFile(path.join(root,file),'utf8')).replace(/\r\n/g,'\n'));
      actual=createHash('sha1').update('blob '+normalized.length+'\0').update(normalized).digest('hex');
    }
    if(actual!==expectedAssets.get(file))throw new Error('CDN snapshot differs from local asset '+file+'. Push the resource commit and update cdnBase, or disable CDN.');
    expectedAssets.delete(file);
  }
  hash.update(fileHash.digest());
}
if(expectedAssets.size)throw new Error('CDN snapshot contains assets removed locally. Update cdnBase or disable CDN.');
const version = hash.digest('hex').slice(0, 20);
await writeFile(path.join(root, 'core/cache-version.js'), `/* Generated by node tools/prepare-deploy.mjs; do not edit. */\nself.GT_CACHE_VERSION = '${version}';\n`);
console.log(`Prepared ${files.length} runtime files; cache version ${version}`);
